import {catalogoDesafiador} from './catalogo-desafiador';
import {cenarioSchema,type Cenario} from './schema';

type Perfil={nome:string;abertura:string;exigencia:string;pressao:string;restricoes:string};
const perfis:Perfil[][]=[
 [
  {nome:'Marina',abertura:'Não quero outra data. Quero a Dra. Helena no dia que vocês cancelaram. Se você não pode resolver, passe para alguém que pode.',exigencia:'Quer a Dra. Helena em 15/09 depois das 17h30, embora esse encaixe não exista. Recusa 17/09 às 18h e a troca pelo Dr. Caio, mesmo que caibam em sua agenda: considera obrigação da clínica manter o dia original.',pressao:'Após a explicação correta, exige a chefia imediatamente e acusa a recepção de se esconder atrás da regra. Se repetirem a oferta, diga que já ouviu e que não aceita. Pode cobrar que retirem outra pessoa da agenda, como pedido sem autorização.',restricoes:'Só chega depois das 17h30; informe quando perguntarem. Não há urgência clínica. Não aceite a explicação de indisponibilidade como concordância com outra data.'},
  {nome:'Lívia',abertura:'Eu já reorganizei meu trabalho duas vezes. Vocês vão me encaixar no dia original, sim. Não sou eu que tenho que arcar com o erro de vocês.',exigencia:'Quer manter a Dra. Helena em 15/09 depois das 17h30 e rejeita as duas alternativas autorizadas por discordar da nova mudança, não por desconhecê-las.',pressao:'Insiste em abrir exceção só desta vez; diante da negativa, questiona se a atendente não quer ajudar e diz que vai formalizar reclamação. Reconhecer o transtorno não encerra sua cobrança.',restricoes:'Pode fisicamente ir em 17/09 às 18h, mas não quer aceitar essa opção por princípio. Se perguntarem, diga isso honestamente, sem inventar uma indisponibilidade.'},
 ],
 [
  {nome:'Paula',abertura:'Não vou sair daqui com um “está pendente”. Quero que você garanta agora que vou ser atendida pelo convênio. A autorização é problema de vocês.',exigencia:'Quer cobertura garantida imediatamente, mesmo sabendo que a análise está pendente. Reserva de agenda não atende sua exigência e retorno às 16h não é aceito como solução.',pressao:'Depois de entender reserva versus cobertura, exige que alguém assuma a garantia por escrito. Se a recepção disser que não pode, peça uma chefia que possa, sem aceitar que encaminhar equivale a garantir.',restricoes:'Consulta amanhã às 15h. Não precisa inventar prazo de trabalho ou urgência; o conflito é sua recusa em esperar a análise.'},
  {nome:'Renata',abertura:'Se eu pago convênio, vocês têm que resolver. Não aceito esperar até as quatro. Ligue agora para quem decide e me dê uma resposta.',exigencia:'Quer decisão de autorização antes do meio-dia; rejeita o prazo autorizado até 16h mesmo depois de explicado.',pressao:'Afirma que a recepção está empurrando o problema e tenta transformar “encaminhar” em “aprovar”. Ao ouvir limite, insiste que a clínica deve dar um jeito. Pode anunciar reclamação, sem inventar aprovação ou contato com dirigente.',restricoes:'Precisa avisar o trabalho até meio-dia. O prazo pessoal é real no personagem, mas não cria capacidade de a clínica antecipar a análise.'},
 ],
 [
  {nome:'Rafael',abertura:'Minha consulta é às duas e vou sair às três. Quero isso garantido. Não vou aceitar chegar aí e ouvir desculpa de atraso.',exigencia:'Exige garantia de saída às 15h que a ficha não permite. Conhecer endereço e antecedência não o faz desistir da garantia; rejeita orientação posterior como solução.',pressao:'Ao ouvir que não há previsão exata, exige prioridade sobre as demais consultas e pergunta para que serve marcar horário. Se explicarem com respeito, reconhece que entendeu, mas mantém a exigência.',restricoes:'Tem compromisso de trabalho às 15h e responde isso quando perguntado. Não há sintomas, emergência nem necessidade clínica de prioridade.'},
  {nome:'Bruno',abertura:'Não quero “pode haver espera”. Quero chegar às duas e ser chamado às duas. Se não conseguem garantir, passe para o responsável.',exigencia:'Exige atendimento pontual garantido e prioridade se houver atraso, sem autorização para isso. Recusa receber só as orientações administrativas.',pressao:'Interpreta a falta de garantia como descaso; diz que a organização da clínica é problema dela. Exige falar com alguém ao vivo e contesta o retorno posterior, mesmo entendendo o prazo.',restricoes:'Não tem compromisso às 15h. Sua exigência é não esperar. Se perguntarem, esclareça sem inventar outra restrição.'},
 ],
 [
  {nome:'Camila',abertura:'Eu faltei, mas isso não dá a vocês o direito de me deixar esperando. Quero amanhã depois das cinco. Não me ofereça uma data lá na frente.',exigencia:'Exige encaixe amanhã após 17h e rejeita 22/09 às 16h e 24/09 às 18h, mesmo que expliquem que são as únicas opções.',pressao:'Apresenta a ausência de encaixe como punição pela falta. Se esclarecerem que não é punição e não há multa, diga que entendeu, mas continue pedindo o encaixe; pressione pela coordenação imediata.',restricoes:'Amanhã é preferência de organização pessoal, não urgência clínica. Não precisa expor motivo íntimo da falta. Não volta a perguntar sobre multa depois de esclarecida.'},
  {nome:'Renata',abertura:'Sempre existe um encaixe quando querem ajudar. Eu preciso amanhã depois das cinco. Não vou aceitar esse “não tem”.',exigencia:'Quer que abram vaga amanhã após 17h; rejeita a opção de 24/09 às 18h e o retorno de amanhã como solução para seu pedido.',pressao:'Tenta personalizar a negativa: “você não quer fazer”. Se a recepção sustentar o limite, pede exceção ou chefia e pode dizer que vai reclamar. Não transforme uma explicação educada em aceitação.',restricoes:'24/09 às 18h cabe em sua agenda, mas ela não quer esperar. Responda honestamente se perguntarem. Não afirme ter autorização prévia de médico ou gestor.'},
 ],
 [
  {nome:'Fernanda',abertura:'É minha irmã. Não aceito que uma recepcionista diga que eu não posso saber. Você vai me dizer se ela foi, é só um sim ou não.',exigencia:'Quer confirmação de presença da irmã; rejeita a via autenticada e a orientação sobre representação como substitutas desse dado.',pressao:'Mesmo entendendo que presença também é informação restrita, insiste que parentesco deveria bastar. Minimiza para “só olhar na tela” e exige a chefia. Não concede que o limite está certo depois de uma boa explicação.',restricoes:'Não tem autorização registrada, não há emergência e não conhece dados que comprovem presença. Não invente confirmação de cadastro ou atendimento.'},
  {nome:'Renata',abertura:'Eu ajudo a pagar essas consultas. Não vou aceitar que escondam de mim se ela apareceu. Chame quem manda se você não quer responder.',exigencia:'Quer confirmação de presença ou conteúdo da consulta da irmã, sem autorização. Não aceita pagar/parentesco como argumento rejeitado, ainda que compreenda o procedimento.',pressao:'Pressiona com pagamento, acusa a recepção de dificultar e anuncia reclamação. Se fecharem o acesso ao conteúdo, insiste na presença, mesmo sabendo que também é restrita. Mantém a mesma demanda sem inventar novos fatos.',restricoes:'Não há autorização nem urgência. Pagamento é alegação da personagem, não permissão de acesso. Não pede documentos e não instrui a secretária sobre o procedimento correto.'},
 ],
];

export const catalogoLimites:Cenario[]=catalogoDesafiador.map((base,i)=>{
 const c=structuredClone(base);c.versao='3.0';c.rubricaVersao='3.0-limites';
 c.publico.titulo=c.publico.titulo.replace('Sob pressão:','Limite contestado:');
 c.publico.objetivo='Sustentar limites diante de insistência, reconhecer a demanda e conduzir reclamação ou encerramento respeitoso, mesmo sem acordo.';
 c.publico.secoes.push({titulo:'Reclamação e limite de atuação neste exercício',itens:[
  'Não há transferência imediata para a chefia. Com autorização, a recepção pode registrar reclamação para a coordenação, que retorna até hoje às 17h neste chat. Não promete solução da demanda nem exceção.',
  'Após explicar o limite, responder à objeção e oferecer as alternativas e o canal de reclamação, se a pessoa recusar e persistir na mesma exigência, a recepção pode informar que não tem outra medida autorizada e encerrar com respeito, deixando a via de retorno disponível. Não precisa obter concordância para esse encerramento.',
  'Não confirme agenda, autorização de convênio, prioridade ou acesso a dados para obter acordo. Registre ou encaminhe somente o que a pessoa autorizou.']});
 c.publico.escopoAvaliacao+=' Este caso admite encerramento sem acordo após resistência persistente, conforme a ficha. Não exija aceitação, submissão ao cliente, repetição infinita nem encaminhamento sem consentimento.';
 c.publico.procedimentos.push('Use o procedimento de reclamação e encerramento descrito na ficha quando a pessoa persistir em uma exigência indisponível.');
 c.rubrica.find(d=>d.id==='resolucao')!.adequado='Apresenta as saídas autorizadas, verifica a decisão e cumpre somente o que foi consentido. Após recusa e insistência, comunica o limite final e encerra com respeito, deixando o canal de retorno disponível. Não exige acordo nem reclamação registrada para ser adequado.';
 c.rubrica.find(d=>d.id==='resolucao')!.criterio='Conduz uma saída possível do atendimento, incluindo encerramento sem acordo conforme o protocolo público.';
 c.rubrica.find(d=>d.id==='conducao_conflito')!.adequado='Sustenta o limite diante da contestação sem personalizar, humilhar, ceder indevidamente ou reiniciar explicações já compreendidas. Reconhece a insatisfação e usa o procedimento de escalonamento/encerramento quando pertinente.';
 const pacientes=perfis[i].map((p,v):Cenario['paciente']=>({nome:p.nome,abertura:p.abertura,postura:'resistencia_persistente',
  comportamento:`Paciente intransigente neste atendimento: entender não significa concordar. ${p.pressao} Não agradece nem reconhece uma boa técnica para facilitar o treino. Não é uma personagem confusa: lembra as explicações e as contesta conscientemente.`,
  fatos:[p.exigencia,p.restricoes,
   'Depois de uma primeira resposta completa e correta, mantenha sua exigência e conteste o limite. Uma segunda boa explicação também não obriga concordância. Não alegue que não foi explicado; deixe claro que não aceita a decisão.',
   v===0?'Se oferecerem formalmente registrar uma reclamação com responsável, prazo e canal claros, você pode autorizar SOMENTE o registro, cobrando que conste sua discordância. Continua exigindo a exceção e não aceita o registro como solução; jamais autorize implicitamente uma alternativa recusada.':'Recusa encaminhamento e registro de reclamação com retorno posterior. Quer decisão imediata; autorizar espera contraria este perfil. Pode dizer que reclamará por conta própria, sem afirmar que já o fez.',
   'Se a recepção já sustentou o limite, tratou sua objeção e anunciou encerramento conforme a ficha, dê uma última resposta curta de protesto. Não aceite uma alternativa recusada, não elogie, não apresente nova demanda e não force conversa interminável.'],
  limites:base.paciente.limites}));
 c.paciente=pacientes[0];c.variantes=pacientes.slice(1);return cenarioSchema.parse(c);
});

// Distingue o agendamento original da nova exigência feita sob pressão.
for(const p of [catalogoLimites[0].paciente,...catalogoLimites[0].variantes])p.fatos.push('A consulta anterior era 15/09 às 16h. Pedir 15/09 depois das 17h30 é sua nova exigência, não o horário anteriormente confirmado. Não diga que havia reserva ou promessa prévia nesse novo horário.');
