'use client';
import { useEffect, useState, useRef } from 'react';
import { fetchAuth } from '@/lib/auth/fetch-auth';
import { EditorCenario } from './editor';
import styles from './treino.module.css';

export default function GestaoRecepcao({empresaId,visao,admin}:{empresaId:string;visao:'equipe'|'cenarios';admin:boolean}) {
 const [dados,setDados]=useState<any>(null),[erro,setErro]=useState(''),[busy,setBusy]=useState(false);
 const [dias,setDias]=useState('30'),[testes,setTestes]=useState(false),[detalhe,setDetalhe]=useState<any>(null),[editor,setEditor]=useState<any>(null);
 const [parecer,setParecer]=useState('concordo'),[motivo,setMotivo]=useState(''),[dimensoes,setDimensoes]=useState<string[]>([]);
 const pending=useRef<string|null>(null),generation=useRef(0);
 async function api(params:Record<string,string>={},body?:unknown) {
  const q=new URLSearchParams({...params,...(admin?{empresaId}:{})});
  const r=await fetchAuth(`/api/recepcao/gestao?${q}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body as object,...(admin?{empresaId}:{})})}:{cache:'no-store'});
  const d=await r.json();if(!r.ok) throw new Error(d.campos?.length ? d.campos.map(c=>`${c.campo}: ${c.erro}`).join('\n'):d.error||'Não foi possível carregar.');return d;
 }
 async function carregar(ticket=generation.current) {
  const d=await api({visao,dias,testes:testes?'1':'0'});if(ticket===generation.current) setDados(d);
 }
 useEffect(()=>{const ticket=++generation.current;setDados(null);setDetalhe(null);setEditor(null);setErro('');setBusy(true);carregar(ticket).catch(e=>{if(ticket===generation.current)setErro(e.message)}).finally(()=>{if(ticket===generation.current)setBusy(false)});return()=>{generation.current++}},[visao,dias,testes,empresaId]);
 async function abrir(id:string) {setBusy(true);setErro('');try{setDetalhe(await api({sessaoId:id}));setMotivo('');setDimensoes([]);pending.current=null;}catch(e){setErro(e.message)}finally{setBusy(false)}}
 async function revisar() {if(busy)return;setBusy(true);setErro('');try{pending.current||=crypto.randomUUID();await api({}, {acao:'revisar',sessaoId:detalhe.sessao.id,requestId:pending.current,parecer,motivo,dimensoes});pending.current=null;setDetalhe(await api({sessaoId:detalhe.sessao.id}));setMotivo('');await carregar()}catch(e){setErro(e.message)}finally{setBusy(false)}}
 async function salvar(cmd:any) {setBusy(true);setErro('');try{const d=await api({},cmd);setEditor(cmd.acao==='arquivar'?null:d.cenario);await carregar();return d.cenario;}catch(e){setErro(e.message);throw e}finally{setBusy(false)}}
 if(editor) return <section className={styles.management}>{erro&&<p role="alert" className={styles.error}>{erro}</p>}<EditorCenario key={editor.id||'novo'} registro={editor} busy={busy} salvar={salvar} fechar={()=>{setEditor(null);setErro('')}}/></section>;
 return <section className={styles.management} aria-label={visao==='equipe'?'Acompanhamento da equipe':'Biblioteca de cenários'}>
  <header className={styles.sectionHead}><div><p className={styles.eyebrow}>{visao==='equipe'?'A prática, acompanhada':'Casos para praticar'}</p><h2>{visao==='equipe'?'Equipe e revisões':'Biblioteca de cenários'}</h2></div>
  {visao==='equipe'?<div className={styles.filters}><label>Período<select value={dias} disabled={busy} onChange={e=>setDias(e.target.value)}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></label>{admin&&<label className={styles.checkLabel}><input type="checkbox" checked={testes} disabled={busy} onChange={e=>setTestes(e.target.checked)}/> Incluir testes administrativos</label>}</div>:<button className={styles.primary} disabled={busy||!dados?.cenarios?.length} onClick={()=>setEditor({conteudo:{...structuredClone(dados.cenarios[0].conteudo),id:'novo-caso',publico:{...structuredClone(dados.cenarios[0].conteudo.publico),titulo:'Novo caso'}}})}>Criar caso</button>}</header>
  {erro&&<p role="alert" className={styles.error}>{erro}</p>}
  {busy&&<p role="status">Carregando…</p>}
  {visao==='cenarios'&&dados&&<div className={styles.caseGrid}>{dados.cenarios.map(r=><article key={r.id}><p className={styles.eyebrow}>{r.empresa_id?'Da clínica':'Catálogo Vertho'} · {r.estado}</p><h3>{r.conteudo.publico.titulo}</h3><p>{r.conteudo.publico.objetivo}</p><small>{r.versao} · {r.conteudo.rubrica.length} competências · {1+(r.conteudo.variantes?.length||0)} pacientes</small><button className={styles.secondary} disabled={busy} onClick={()=>setEditor(r.estado==='rascunho'&&r.empresa_id? r : {conteudo:structuredClone(r.conteudo)})}>{r.estado==='rascunho'&&r.empresa_id?'Editar rascunho':'Criar nova versão'}</button>{r.empresa_id&&r.estado!=='arquivado'&&<button className={styles.link} disabled={busy} onClick={()=>{if(window.confirm('Arquivar esta versão? Treinos anteriores continuam disponíveis.'))salvar({acao:'arquivar',id:r.id,revisao:r.revisao}).catch(()=>{})}}>Arquivar</button>}</article>)}</div>}
  {visao==='equipe'&&dados&&<>
   <div className={styles.metrics}><div><strong>{dados.pessoas.filter(p=>p.iniciadas>0).length}/{dados.pessoas.length}</strong><span>Pessoas ativas que treinaram</span></div><div><strong>{dados.concluidas}/{dados.iniciadas}</strong><span>Treinos concluídos</span></div><div><strong>{dados.pendentes}</strong><span>Relatórios sem revisão</span></div></div>
   <p className={styles.small}>Os resultados abaixo pertencem ao período selecionado. Compare apenas o mesmo caso, versão da rubrica e cobertura. Testes administrativos são identificados separadamente.</p>
   {dados.grupos.map(g=><details key={g.chave} className={styles.group}><summary>{g.titulo} · {g.sessoes} treinos · média {g.media===null?'—':g.media.toFixed(1)} · cobertura {g.cobertura}%</summary><p className={styles.small}>Versão {g.versao} · {g.criticas} com ocorrência crítica</p><div className={styles.tableWrap}><table><thead><tr><th>Competência</th><th>Adequado</th><th>Parcial</th><th>Insuficiente</th><th>Não observado</th></tr></thead><tbody>{Object.entries(g.dimensoes).map(([id,d]:[string,any])=><tr key={id}><th>{d.nome}</th><td>{d.adequado}</td><td>{d.parcial}</td><td>{d.insuficiente}</td><td>{d.nao_observavel}</td></tr>)}</tbody></table></div></details>)}
   <details className={styles.group}><summary>Participação por pessoa</summary>{dados.pessoas.map(p=><p key={p.id}>{p.nome} · {p.concluidas} concluídos / {p.iniciadas} iniciados</p>)}{!dados.pessoas.length&&<p>Nenhum colaborador no seu escopo de acompanhamento.</p>}</details>
   <h3>Atendimentos para acompanhar</h3><div className={styles.tableWrap}><table><thead><tr><th>Pessoa / caso</th><th>Data</th><th>Resultado</th><th>Revisão</th><th>Ação</th></tr></thead><tbody>{dados.sessoes.map(s=><tr key={s.id}><td><strong>{s.nome}</strong><br/>{s.titulo}</td><td>{new Date(s.data).toLocaleDateString('pt-BR')}</td><td>{s.nota===null?'Em andamento':`${s.nota}/100`}{s.critica?' · atenção':''}</td><td>{s.revisao||'Pendente'}</td><td><button className={styles.link} disabled={busy} onClick={()=>abrir(s.id)}>Abrir atendimento</button></td></tr>)}</tbody></table>{!dados.sessoes.length&&<p className={styles.empty}>Nenhum treino neste período. A participação aparecerá quando a equipe começar.</p>}</div>
   {dados.operacao&&<details className={styles.group}><summary>Operação e custo de IA</summary><p>{dados.operacao.tentativas} tentativas · {dados.operacao.emAberto} sem finalização registrada · custo conhecido US$ {dados.operacao.custoConhecidoUsd.toFixed(4)}</p><p>Rejeições do avaliador: {dados.operacao.avaliacoesRejeitadas}/{dados.operacao.avaliacoes} · {dados.operacao.taxaRejeicao==null?'—':`${dados.operacao.taxaRejeicao.toFixed(1)}%`}</p><p className={styles.small}>Uma tentativa sem uso registrado ou sem custo apurado não equivale a custo zero. Chamadas anteriores à instrumentação não entram nesta conta.</p>{Object.entries(dados.operacao.rejeicoes).map(([k,v])=><p key={k}>{k}: {String(v)}</p>)}<p>Modelos efetivos: {dados.operacao.modelos.join(', ')||'Ainda sem uso registrado'}</p>{dados.operacao.porSessao.map(s=><p key={s.id}>Treino {s.id.slice(0,8)} · {s.tentativas} tentativas · US$ {s.custoConhecidoUsd.toFixed(4)} · {s.semUsoRegistrado} sem uso registrado · {s.semCustoRegistrado||0} com custo desconhecido</p>)}</details>}
  </>}
  {detalhe&&<section className={styles.review} aria-label="Revisão do atendimento"><header className={styles.sectionHead}><h2>{detalhe.sessao.cenario.titulo}</h2><button className={styles.secondary} onClick={()=>setDetalhe(null)}>Fechar revisão</button></header>
   <div className={styles.reviewColumns}><div><h3>Conversa preservada</h3>{detalhe.sessao.historico.map(m=><blockquote key={m.id}><strong>{m.role==='user'?'Secretária':detalhe.sessao.cenario.nomePaciente} · {m.id}</strong><p>{m.content}</p></blockquote>)}</div><div><h3>Avaliação original da IA</h3>{detalhe.sessao.relatorio?.dimensoes.map(d=><article key={d.id}><h4>{d.nome||detalhe.sessao.cenario.competencias?.find(c=>c.id===d.id)?.nome||d.id} · {d.classificacao}</h4><p>{d.justificativa}</p>{d.evidencias.map((r,i)=><blockquote key={i}>{r.mensagemId}: {r.trecho}</blockquote>)}</article>)||<p>Este atendimento ainda não tem relatório.</p>}</div></div>
   {detalhe.podeRevisar&&detalhe.sessao.relatorio&&<form className={styles.editor} onSubmit={e=>{e.preventDefault();revisar()}}><h3>Registrar parecer</h3><p>A revisão fica anexada ao atendimento. A nota original não é sobrescrita.</p><label>Parecer<select value={parecer} onChange={e=>{setParecer(e.target.value);pending.current=null}}><option value="concordo">Concordo</option><option value="parcialmente">Concordo parcialmente</option><option value="discordo">Discordo</option></select></label><fieldset><legend>Competências comentadas (opcional)</legend>{detalhe.sessao.relatorio.dimensoes.map(d=><label className={styles.checkLabel} key={d.id}><input type="checkbox" checked={dimensoes.includes(d.id)} onChange={e=>{pending.current=null;setDimensoes(e.target.checked?[...dimensoes,d.id]:dimensoes.filter(id=>id!==d.id))}}/>{d.nome||detalhe.sessao.cenario.competencias?.find(c=>c.id===d.id)?.nome||d.id}</label>)}</fieldset><label>Motivo e evidências<textarea value={motivo} maxLength={4000} required onChange={e=>{setMotivo(e.target.value);pending.current=null}} placeholder="Explique o parecer com base nas falas acima."/></label><button className={styles.primary} disabled={busy||!motivo.trim()}>Salvar revisão</button></form>}
   {!detalhe.podeRevisar&&<p className={styles.small}>A revisão exige outra pessoa com permissão de acompanhamento e registro.</p>}
   <h3>Revisões registradas</h3>{detalhe.revisoes.map(r=><article className={styles.group} key={r.id}><strong>{r.revisor_nome} · {r.parecer}</strong><p>{r.motivo}</p><small>{new Date(r.created_at).toLocaleString('pt-BR')}</small></article>)}{!detalhe.revisoes.length&&<p>Ainda não há parecer humano.</p>}
  </section>}
 </section>;
}
